### ISSUE TITLE
Where to put this?

### ISSUE THREAD

**Issue by DreamsUnderStars** [purringInsanity/EquipmentKeeper#1]
Does it go in the base folder, or somewhere else? Does it need bepinex? Instalation notes would be helpful.

**Comment by purringInsanity** [comment]
This mod requires BepInEx6. There is a prebuilt BepInEx package for Core Keeper on thunderstore. 
Once BepInEx is installed, this mod will go in the plugins folder. 
I have added installation notes to the readme and will have them on thunderstore as soon as possible. 

link to BepInEx Core Keeper package. https://core-keeper.thunderstore.io/package/BepInEx/BepInExPack_Core_Keeper/

Thank you.

**Comment by DreamsUnderStars** [comment]
Thanks for the reply. :)
