### ISSUE TITLE
Update Problems

### ISSUE THREAD

**Issue by Dinoblaster** [purringInsanity/EquipmentKeeper#3]
After updating to the newest version the mod still doesn't function correctly. The tools still continue to loose durability, and just to make sure it wasn't due to an old world or anything I made a new world and it still doesn't work

**Comment by purringInsanity** [comment]
Have you updated to the newest BepInEx package on thunderstore? Equipment Keeper is dependent on that. If you haven't, please try that and let me know if it fixes it for you?

**Comment by Dinoblaster** [comment]
I have, unless Thunderstore is somehow hiding the fact BepInEx has an available update then no, but it is on version 2.0.1 for Bep and I always update to the latest version with the mods so tbh it's probably EquipmentKeeper

these are the other Mods I have installed excluding Bep and Keeper just in case there is conflict (and just to clarify the Deprecated mods aren't the problem since I tried with them turned off)

![image](https://user-images.githubusercontent.com/118231125/202052664-2e5611e9-d2ae-46b3-b70c-fab0f75ff409.png)

**Comment by Dinoblaster** [comment]
seems EquipmentKeeper isn't the only one not working either, AutoFish also isn't working so there is probably something wrong with version you used as a basis for the mod update

**Comment by purringInsanity** [comment]
Alrighty, thanks. I'll get to looking.

**Comment by purringInsanity** [comment]
Okay, I've uninstalled and wiped my corekeeper setup, downloaded every mod available on r2modman, and can't replicate the issue. 

What operating system are you using and Could you post your BepInEx LogOutput.Log file?

**Comment by Dinoblaster** [comment]
Here it is, I believe this is it

[LogOutput.log](https://github.com/purringInsanity/EquipmentKeeper/files/10027281/LogOutput.log)

**Comment by Dinoblaster** [comment]
if you don't have the problem then do you recommend I uninstall all the mods and then re-install them?

**Comment by purringInsanity** [comment]
Your log is showing BepInEx be-553 build, current BepInEx core package should be at be-656. Try uninstalling and reinstalling, and let me know if that works.

**Comment by Dinoblaster** [comment]
just Bep correct?

**Comment by purringInsanity** [comment]
Start with bepin, if that doesn't work, reinstall the mods.

**Comment by Dinoblaster** [comment]
didn't work, not to mention uninstalling Bep Basically uninstalls all the other ones. But as I look at the description of Bep it says the last time it was updated on September 25 which is most likely the main reason everything isn't working

how do I manually update it to the new version

**Comment by Dinoblaster** [comment]
I inquired about the issue as well and Kremnev8 has stated that the manager doesn't remove the outdated files preventing Bep from moving past be-553.

The fix was to completely delete the Thunderstore Profile, so the issue was with the manager it's self rather then any mod apparently
